#spring.data.mongodb.uri=mongodb+srv://shrutinar27_db_user:4tX1LvpDwO2sdU99@cluster0.x1zggjd.mongodb.net/journaldb?retryWrites=true&w=majority
#spring.data.mongodb.auto-index-creation=true

#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://shrutinar27_db_user:4tX1LvpDwO2sdU99@cluster0.x1zggjd.mongodb.net/journaldb?retryWrites=true&w=majority
#      database: journaldb
#      auto-index-creation: true



